# Baseline Content-Based Recommendation

## Objective

Build and evaluate a TF-IDF recommendation system using the processed event dataset.

This notebook establishes a baseline that will later be compared against semantic embedding models.

In [1]:
import pandas as pd

df = pd.read_parquet("../data/processed/events.parquet")

df.head()

,event_id,event_name,genre,segment,date,time,city,country,venue_id,latitude,longitude,url,event_text
0,16djZbVF7G7ncoa,PITBULL - Official Premium Ticket and Hotel Ex...,pop,music,2026-07-10,14:01:00,london,Great Britain,KovZ9177gxV,51.507432,-0.165708,https://easol.link/46mx,PITBULL - Official Premium Ticket and Hotel Ex...
1,LvZ18Q0SLwvfxWGngd52d,England Vs Norway - Entry + Drink,soccer,sports,2026-07-11,22:00:00,london,Great Britain,KovZ9177hqV,NaN,NaN,https://www.universe.com/events/england-vs-nor...,England Vs Norway - Entry + Drink soccer sport...
2,LvZ18Q0_grnqitMu1wS7E,Rehab_LDN,dance/electronic,music,2026-07-11,23:45:00,london,Great Britain,KovZpZAnaJaA,51.538590,-0.143343,https://www.universe.com/events/rehab_ldn-tick...,Rehab_LDN dance/electronic music london
3,LvZ18Q9SJj0LBYZZlJpGR,Loveball,dance/electronic,music,2026-07-11,22:00:00,amsterdam,Netherlands,Z598xZbpZk6e1,52.395320,4.874830,https://www.universe.com/events/loveball-ticke...,Loveball dance/electronic music amsterdam
4,LvZ18QxvnZQDw78ZJI7Lw,Soul City: House music every Saturday,undefined,music,2026-07-11,23:45:00,london,Great Britain,KovZpZAnaJaA,51.538590,-0.143343,https://www.universe.com/events/soul-city-hous...,Soul City: House music every Saturday undefine...

In [2]:
from culture_compass.recommender.content_based import (
    ContentBasedRecommender,
)

In [3]:
from culture_compass.search.event_search import EventSearch

In [4]:
recommender = ContentBasedRecommender()

recommender.fit(df)

In [5]:
df[
    df["event_name"]
    .str.contains(
        "abba",
        case=False,
        na=False,
    )
]

,event_id,event_name,genre,segment,date,time,city,country,venue_id,latitude,longitude,url,event_text
53,1AgZkCKGkewBaM3,ABBA Voyage,pop,music,2026-07-12,18:00:00,london,Great Britain,KovZ9177E07,51.533274,-0.013623,https://theatre.ticketmaster.co.uk/book/1H8DJ-...,ABBA Voyage pop music london
70,1AgZkCKGkewiyUp,ABBA Voyage,pop,music,2026-07-12,13:00:00,london,Great Britain,KovZ9177E07,51.533274,-0.013623,https://theatre.ticketmaster.co.uk/book/1H8DJ-...,ABBA Voyage pop music london
93,1AgZkCKGkeS6_zO,ABBA Voyage,pop,music,2026-07-13,19:45:00,london,Great Britain,KovZ9177E07,51.533274,-0.013623,https://theatre.ticketmaster.co.uk/book/1H8DJ-...,ABBA Voyage pop music london
340,1AgZkCKGkeSfyB1,ABBA Voyage,pop,music,2026-07-16,19:45:00,london,Great Britain,KovZ9177E07,51.533274,-0.013623,https://theatre.ticketmaster.co.uk/book/1H8DJ-...,ABBA Voyage pop music london
416,1AgZkCKGkeSxaBw,ABBA Voyage,pop,music,2026-07-17,19:45:00,london,Great Britain,KovZ9177E07,51.533274,-0.013623,https://theatre.ticketmaster.co.uk/book/1H8DJ-...,ABBA Voyage pop music london
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4586,17u8v0G65M6R_95,ABBA Voyage,pop,music,2027-01-29,19:45:00,london,Great Britain,KovZ9177E07,51.533274,-0.013623,https://theatre.ticketmaster.co.uk/book/1H8DJ-...,ABBA Voyage pop music london
4604,17u8v0G65M6D_9s,ABBA Voyage,pop,music,2027-01-30,15:00:00,london,Great Britain,KovZ9177E07,51.533274,-0.013623,https://theatre.ticketmaster.co.uk/book/1H8DJ-...,ABBA Voyage pop music london
4605,17u8v0G65MF6tbj,ABBA Voyage,pop,music,2027-01-30,19:45:00,london,Great Britain,KovZ9177E07,51.533274,-0.013623,https://theatre.ticketmaster.co.uk/book/1H8DJ-...,ABBA Voyage pop music london
4611,17u8v0G65MFLaQ5,ABBA Voyage,pop,music,2027-01-31,18:00:00,london,Great Britain,KovZ9177E07,51.533274,-0.013623,https://theatre.ticketmaster.co.uk/book/1H8DJ-...,ABBA Voyage pop music london
5052,Z698xZC2Z1kQf4yxf,ABBAMANIA: 50 JAHRE THANK YOU FOR THE MUSIC| B...,rock,music,2027-05-14,20:00:00,berlin,Germany,Z698xZC2Za74L,52.505730,13.443140,https://www.ticketmaster.de/event/abbamania-50...,ABBAMANIA: 50 JAHRE THANK YOU FOR THE MUSIC| B...

In [6]:
event_name = "ABBA Voyage"

df.loc[
    df["event_name"] == event_name,
    ["event_id", "event_name"]
]

             event_id   event_name
53    1AgZkCKGkewBaM3  ABBA Voyage
70    1AgZkCKGkewiyUp  ABBA Voyage
93    1AgZkCKGkeS6_zO  ABBA Voyage
340   1AgZkCKGkeSfyB1  ABBA Voyage
416   1AgZkCKGkeSxaBw  ABBA Voyage
...               ...          ...
4579  17u8v0G65M6NapR  ABBA Voyage
4586  17u8v0G65M6R_95  ABBA Voyage
4604  17u8v0G65M6D_9s  ABBA Voyage
4605  17u8v0G65MF6tbj  ABBA Voyage
4611  17u8v0G65MFLaQ5  ABBA Voyage

[191 rows x 2 columns]

In [7]:
recommender.recommend_same_event_dates(
    event_id="17u8v0G65MFLaQ5", event_name="ABBA Voyage"
)

,event_name,genre,city,date,url
0,ABBA Voyage,pop,london,2026-07-12,https://theatre.ticketmaster.co.uk/book/1H8DJ-...
1,ABBA Voyage,pop,london,2026-07-12,https://theatre.ticketmaster.co.uk/book/1H8DJ-...
2,ABBA Voyage,pop,london,2026-07-13,https://theatre.ticketmaster.co.uk/book/1H8DJ-...
3,ABBA Voyage,pop,london,2026-07-16,https://theatre.ticketmaster.co.uk/book/1H8DJ-...
4,ABBA Voyage,pop,london,2026-07-17,https://theatre.ticketmaster.co.uk/book/1H8DJ-...

In [8]:
recommender.recommend_similar_events(
    "17u8v0G65MFLaQ5"
)

,event_name,genre,city,date,venue_id,url,similarity
0,WE ARE THEM,pop,amsterdam,2026-08-02,Z598xZbpZd6ak,https://www.ticketmaster.nl/event/we-are-them-...,0.429363
1,We All Sing ABBA | Premium Seats,pop,amsterdam,2026-11-25,Z598xZbpZk661,https://www.ticketmaster.nl/event/-we-all-sing...,0.366138
2,Take Van,pop,london,2026-10-15,KovZ9177yO7,https://www.ticketweb.uk/event/take-van-colour...,0.319510
3,Sports,pop,london,2026-10-24,KovZ9177Akf,https://www.ticketweb.uk/event/sports-the-gara...,0.301273
4,MUNA,pop,london,2026-11-18,KovZpZAtadaA,https://www.ticketmaster.co.uk/muna-london-18-...,0.278332

In [9]:
search = EventSearch(df)

search.search("abba")

,event_id,event_name,genre,city,country,date,url
0,1AgZkCKGkewBaM3,ABBA Voyage,pop,london,Great Britain,2026-07-12,https://theatre.ticketmaster.co.uk/book/1H8DJ-...
1,1AgZkCKGkewiyUp,ABBA Voyage,pop,london,Great Britain,2026-07-12,https://theatre.ticketmaster.co.uk/book/1H8DJ-...
2,1AgZkCKGkeS6_zO,ABBA Voyage,pop,london,Great Britain,2026-07-13,https://theatre.ticketmaster.co.uk/book/1H8DJ-...
3,1AgZkCKGkeSfyB1,ABBA Voyage,pop,london,Great Britain,2026-07-16,https://theatre.ticketmaster.co.uk/book/1H8DJ-...
4,1AgZkCKGkeSxaBw,ABBA Voyage,pop,london,Great Britain,2026-07-17,https://theatre.ticketmaster.co.uk/book/1H8DJ-...
5,1AgZkCKGkeSHtH9,ABBA Voyage,pop,london,Great Britain,2026-07-18,https://theatre.ticketmaster.co.uk/book/1H8DJ-...
6,1AgZkCKGkeSR_D3,ABBA Voyage,pop,london,Great Britain,2026-07-18,https://theatre.ticketmaster.co.uk/book/1H8DJ-...
7,1AgZkCKGkeV1aWk,ABBA Voyage,pop,london,Great Britain,2026-07-19,https://theatre.ticketmaster.co.uk/book/1H8DJ-...
8,1AgZkCKGkeV9_TG,ABBA Voyage,pop,london,Great Britain,2026-07-19,https://theatre.ticketmaster.co.uk/book/1H8DJ-...
9,1AgZkCKGkeVP1Zd,ABBA Voyage,pop,london,Great Britain,2026-07-20,https://theatre.ticketmaster.co.uk/book/1H8DJ-...
10,1AgZkCKGkeVwQv6,ABBA Voyage,pop,london,Great Britain,2026-07-23,https://theatre.ticketmaster.co.uk/book/1H8DJ-...
11,1AgZkCKGkeVTneA,ABBA Voyage,pop,london,Great Britain,2026-07-24,https://theatre.ticketmaster.co.uk/book/1H8DJ-...
12,1AgZkCKGkegu1k9,ABBA Voyage,pop,london,Great Britain,2026-07-25,https://theatre.ticketmaster.co.uk/book/1H8DJ-...
13,1AgZkCKGkegQ1Gc,ABBA Voyage,pop,london,Great Britain,2026-07-25,https://theatre.ticketmaster.co.uk/book/1H8DJ-...
14,1AgZkCKGkegEQuJ,ABBA Voyage,pop,london,Great Britain,2026-07-26,https://theatre.ticketmaster.co.uk/book/1H8DJ-...
15,1AgZkCKGkegVBCq,ABBA Voyage,pop,london,Great Britain,2026-07-26,https://theatre.ticketmaster.co.uk/book/1H8DJ-...
16,1AgZkCKGkeUe12Y,ABBA Voyage,pop,london,Great Britain,2026-07-27,https://theatre.ticketmaster.co.uk/book/1H8DJ-...
17,1AgZkCKGkeU2no1,ABBA Voyage,pop,london,Great Britain,2026-07-30,https://theatre.ticketmaster.co.uk/book/1H8DJ-...
18,1AgZkCKGkeUjBKv,ABBA Voyage,pop,london,Great Britain,2026-07-31,https://theatre.ticketmaster.co.uk/book/1H8DJ-...
19,1AgZk8MGkemXf_V,ABBA Voyage,pop,london,Great Britain,2026-08-01,https://theatre.ticketmaster.co.uk/book/1H8DJ-...

In [10]:
from culture_compass.search.semantic_search import (
    SemanticSearch,
)

In [11]:
search = SemanticSearch()

search.fit(df)

In [12]:
search.search("jazz")

                          event_name genre    city       date     score
0  Alfies Soho - Live Jazz and Blues  jazz  london 2026-08-21  0.555006
1  Alfies Soho - Live Jazz and Blues  jazz  london 2026-08-07  0.555006
2  Alfies Soho - Live Jazz and Blues  jazz  london 2026-08-07  0.555006
3  Alfies Soho - Live Jazz and Blues  jazz  london 2026-07-18  0.555006
4  Alfies Soho - Live Jazz and Blues  jazz  london 2026-08-28  0.555006
5  Alfies Soho - Live Jazz and Blues  jazz  london 2026-07-31  0.555006
6  Alfies Soho - Live Jazz and Blues  jazz  london 2026-07-17  0.555006
7  Alfies Soho - Live Jazz and Blues  jazz  london 2026-07-25  0.555006
8  Alfies Soho - Live Jazz and Blues  jazz  london 2026-07-18  0.555006
9  Alfies Soho - Live Jazz and Blues  jazz  london 2026-07-25  0.555006

In [13]:
search.search("rock concert")

,event_name,genre,city,date,score
0,Van Morrison In Concert,rock,london,2026-09-23,0.555259
1,Van Morrison In Concert,rock,london,2026-09-29,0.555259
2,Van Morrison In Concert,rock,london,2026-09-26,0.555259
3,Van Morrison In Concert,rock,london,2026-09-24,0.555259
4,Van Morrison In Concert,rock,london,2026-09-27,0.555259
5,Van Morrison In Concert,rock,london,2026-09-28,0.555259
6,The Witcher in Concert,classical,london,2026-10-29,0.462745
7,Nick Hakim - I Can See Live: In Concert,rock,berlin,2026-11-11,0.458349
8,Sonic Live In Concert,classical,london,2026-09-30,0.444374
9,Sonic Live In Concert,classical,london,2026-12-18,0.444374

In [14]:
search.search("museum")

,event_name,genre,city,date,score
0,Twist Museum - London's Home of Illusions PEAK,family,london,2026-07-12,0.382908
1,Twist Museum - London's Home of Illusions PEAK,family,london,2026-07-21,0.382908
2,Twist Museum - London's Home of Illusions PEAK,family,london,2026-07-27,0.382908
3,Twist Museum - London's Home of Illusions PEAK,family,london,2026-07-27,0.382908
4,Twist Museum - London's Home of Illusions PEAK,family,london,2026-07-27,0.382908
5,Twist Museum - London's Home of Illusions PEAK,family,london,2026-07-27,0.382908
6,Twist Museum - London's Home of Illusions PEAK,family,london,2026-07-27,0.382908
7,Twist Museum - London's Home of Illusions PEAK,family,london,2026-07-27,0.382908
8,Twist Museum - London's Home of Illusions PEAK,family,london,2026-07-27,0.382908
9,Twist Museum - London's Home of Illusions PEAK,family,london,2026-07-27,0.382908

In [15]:
search.search("opera vienna")

                 event_name    genre    city       date     score
0             Vienna Vienna     rock  london 2026-09-09  0.707455
1                     Tosca    opera  vienna 2026-08-07  0.625389
2               Call It Off     rock  vienna 2026-09-20  0.603056
3                     Dagny     rock  vienna 2027-02-10  0.355358
4       Pitbull - I'm Back!     rock  vienna 2026-11-18  0.348922
5  The Phantom of the Opera  theatre  london 2026-10-19  0.345153
6  The Phantom of the Opera  theatre  london 2026-12-10  0.345153
7  The Phantom of the Opera  theatre  london 2026-11-21  0.345153
8  The Phantom of the Opera  theatre  london 2027-03-06  0.345153
9  The Phantom of the Opera  theatre  london 2027-03-06  0.345153

In [16]:
search.search("classical orchestra berlin")

,event_name,genre,city,date,score
0,YEC 2026 | Orchestra of the Americas & Pendere...,classical,berlin,2026-08-10,0.581057
1,National Symphony Orchestra,classical,vienna,2026-08-14,0.537877
2,Young Euro Classic 2026 | Ulster Youth Orchestra,classical,berlin,2026-08-12,0.463899
3,Young Euro Classic 2026 | Slovenian Youth Orch...,classical,berlin,2026-08-13,0.463899
4,Young Euro Classic 2026 | National Youth Orche...,classical,berlin,2026-08-04,0.433624
5,Young Euro Classic 2026 | Youth Symphony Orche...,classical,berlin,2026-08-01,0.433436
6,Young Euro Classic 2026 | Youth Symphony Orche...,classical,berlin,2026-08-09,0.433436
7,Young Euro Classic 2026 | European Union Youth...,classical,berlin,2026-08-03,0.429888
8,Hook in Concert w/ National Symphony Orchestra,classical,vienna,2026-09-05,0.426014
9,Young Euro Classic 2026 | Jong Metropole Symph...,classical,berlin,2026-08-06,0.412788

In [17]:
event_search= EventSearch(df)

In [18]:
event_search.search(
    query="jazz"
)

,event_id,event_name,genre,city,country,date,url
0,LvZ18QxN5xk01AOZvZbVp,The Cocktail Set from Piano Bar at Red Room St...,jazz,london,Great Britain,2026-07-15,https://www.universe.com/events/the-cocktail-s...
1,LvZ18Q0C4HTwr5AZwuPV7,Live Jazz from the Piano Bar at Red Room Studi...,jazz,london,Great Britain,2026-07-16,https://www.universe.com/events/live-jazz-from...
2,LvZ18QxN7FbzYRYZvNl78,Round 41 - Live Jazz and Fusion Night,jazz,london,Great Britain,2026-07-16,https://www.universe.com/events/round-41-live-...
3,LvZ18Q0C4HTwr5AZwuPVA,Live Jazz from the Piano Bar at Red Room Studi...,jazz,london,Great Britain,2026-07-16,https://www.universe.com/events/live-jazz-from...
4,LvZ18QxN57PgMt8ZvJaA2,Soho Explorer Jazz Sessions from the Piano Bar,jazz,london,Great Britain,2026-07-16,https://www.universe.com/events/soho-explorer-...
5,LvZ18QxN5xk01AOZvZbV9,The Cocktail Set from Piano Bar at Red Room St...,jazz,london,Great Britain,2026-07-16,https://www.universe.com/events/the-cocktail-s...
6,LvZ18QxNAv4ZeYOZvC6_6,Live Jazz from the Piano Bar at Red Room Studi...,jazz,london,Great Britain,2026-07-17,https://www.universe.com/events/live-jazz-from...
7,LvZ18QxNAv4ZeYOZvC6_F,Live Jazz from the Piano Bar at Red Room Studi...,jazz,london,Great Britain,2026-07-17,https://www.universe.com/events/live-jazz-from...
8,LvZ18QxNGBPZeYOZvC6L9,Alfies Soho - Live Jazz and Blues,jazz,london,Great Britain,2026-07-17,https://www.universe.com/events/alfies-soho-li...
9,LvZ18QxNGBPZeYOZvC6Lp,Alfies Soho - Live Jazz and Blues,jazz,london,Great Britain,2026-07-17,https://www.universe.com/events/alfies-soho-li...
10,LvZ18QxNGBN2PM8Zv-dL4,Alfies Soho - Live Jazz and Blues,jazz,london,Great Britain,2026-07-18,https://www.universe.com/events/alfies-soho-li...
11,LvZ18QxNGBN2PM8Zv-dLp,Alfies Soho - Live Jazz and Blues,jazz,london,Great Britain,2026-07-18,https://www.universe.com/events/alfies-soho-li...
12,LvZ18Q-PBHTIWIYZ0N6t0,Homoelectric at Jazz Cafe,dance/electronic,london,Great Britain,2026-07-18,https://www.universe.com/events/homoelectric-a...
13,LvZ18Q0C4HTwr5AZwuPVk,Live Jazz from the Piano Bar at Red Room Studi...,jazz,london,Great Britain,2026-07-23,https://www.universe.com/events/live-jazz-from...
14,LvZ18Q0C4HTwr5AZwuPV6,Live Jazz from the Piano Bar at Red Room Studi...,jazz,london,Great Britain,2026-07-23,https://www.universe.com/events/live-jazz-from...
15,LvZ18QxN7FbzYRYZvNl7o,Round 41 - Live Jazz and Fusion Night,jazz,london,Great Britain,2026-07-23,https://www.universe.com/events/round-41-live-...
16,LvZ18QxNGBPZeYOZvC6Lb,Alfies Soho - Live Jazz and Blues,jazz,london,Great Britain,2026-07-24,https://www.universe.com/events/alfies-soho-li...
17,LvZ18QxNAv4ZeYOZvC6_a,Live Jazz from the Piano Bar at Red Room Studi...,jazz,london,Great Britain,2026-07-24,https://www.universe.com/events/live-jazz-from...
18,LvZ18QxNGBPZeYOZvC6L_,Alfies Soho - Live Jazz and Blues,jazz,london,Great Britain,2026-07-24,https://www.universe.com/events/alfies-soho-li...
19,LvZ18QxNAv4ZeYOZvC6_1,Live Jazz from the Piano Bar at Red Room Studi...,jazz,london,Great Britain,2026-07-24,https://www.universe.com/events/live-jazz-from...

In [19]:
search.search(
    query="jazz")

                          event_name genre    city       date     score
0  Alfies Soho - Live Jazz and Blues  jazz  london 2026-08-21  0.555006
1  Alfies Soho - Live Jazz and Blues  jazz  london 2026-08-07  0.555006
2  Alfies Soho - Live Jazz and Blues  jazz  london 2026-08-07  0.555006
3  Alfies Soho - Live Jazz and Blues  jazz  london 2026-07-18  0.555006
4  Alfies Soho - Live Jazz and Blues  jazz  london 2026-08-28  0.555006
5  Alfies Soho - Live Jazz and Blues  jazz  london 2026-07-31  0.555006
6  Alfies Soho - Live Jazz and Blues  jazz  london 2026-07-17  0.555006
7  Alfies Soho - Live Jazz and Blues  jazz  london 2026-07-25  0.555006
8  Alfies Soho - Live Jazz and Blues  jazz  london 2026-07-18  0.555006
9  Alfies Soho - Live Jazz and Blues  jazz  london 2026-07-25  0.555006

In [20]:
search.search("live jazz piano")

,event_name,genre,city,date,score
0,Live Jazz from the Piano Bar at Red Room Studi...,jazz,london,2026-08-05,0.603113
1,Live Jazz from the Piano Bar at Red Room Studi...,jazz,london,2026-08-28,0.603113
2,Live Jazz from the Piano Bar at Red Room Studi...,jazz,london,2026-08-26,0.603113
3,Live Jazz from the Piano Bar at Red Room Studi...,jazz,london,2026-08-05,0.603113
4,Live Jazz from the Piano Bar at Red Room Studi...,jazz,london,2026-07-23,0.603113
5,Live Jazz from the Piano Bar at Red Room Studi...,jazz,london,2026-07-23,0.603113
6,Live Jazz from the Piano Bar at Red Room Studi...,jazz,london,2026-08-20,0.603113
7,Live Jazz from the Piano Bar at Red Room Studi...,jazz,london,2026-08-20,0.603113
8,Live Jazz from the Piano Bar at Red Room Studi...,jazz,london,2026-07-30,0.603113
9,Live Jazz from the Piano Bar at Red Room Studi...,jazz,london,2026-08-07,0.603113

In [21]:
search.search("classical orchestra")

,event_name,genre,city,date,score
0,National Symphony Orchestra,classical,vienna,2026-08-14,0.574878
1,YEC 2026 | Orchestra of the Americas & Pendere...,classical,berlin,2026-08-10,0.569074
2,Hook in Concert w/ National Symphony Orchestra,classical,vienna,2026-09-05,0.455320
3,Young Euro Classic 2026 | Ulster Youth Orchestra,classical,berlin,2026-08-12,0.434041
4,Young Euro Classic 2026 | Slovenian Youth Orch...,classical,berlin,2026-08-13,0.434041
5,Young Euro Classic 2026 | National Youth Orche...,classical,berlin,2026-08-04,0.405715
6,Young Euro Classic 2026 | Youth Symphony Orche...,classical,berlin,2026-08-09,0.405539
7,Young Euro Classic 2026 | Youth Symphony Orche...,classical,berlin,2026-08-01,0.405539
8,National Symphony Orchestra: Harry Potter and ...,classical,vienna,2026-08-27,0.403495
9,Young Euro Classic 2026 | European Union Youth...,classical,berlin,2026-08-03,0.402219

In [23]:
from culture_compass.search.embedding_search import (
    EmbeddingSearch,
)

c:\Users\kalpo\Desktop\Projects\culture-compass\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [24]:
embedding_search = EmbeddingSearch()

embedding_search.fit(df)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
c:\Users\kalpo\Desktop\Projects\culture-compass\.venv\Lib\site-packages\huggingface_hub\file_download.py:139: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\kalpo\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1128.38it/s]
Batches: 100%|██████████| 161/161 [00:35<00:00,  4.49it/s]

In [25]:
embedding_search.search("jazz")

                              event_name genre    city       date     score
0                                  daoud  jazz  london 2026-12-02  0.706760
1                   Future Jazz Showcase  jazz  london 2026-09-16  0.664497
2                             Albert Lee  jazz  london 2027-05-04  0.641043
3  Round 41 - Live Jazz and Fusion Night  jazz  london 2026-08-27  0.630618
4  Round 41 - Live Jazz and Fusion Night  jazz  london 2026-08-13  0.630618
5  Round 41 - Live Jazz and Fusion Night  jazz  london 2026-08-06  0.630618
6  Round 41 - Live Jazz and Fusion Night  jazz  london 2026-07-30  0.630618
7  Round 41 - Live Jazz and Fusion Night  jazz  london 2026-07-23  0.630618
8  Round 41 - Live Jazz and Fusion Night  jazz  london 2026-08-20  0.630618
9  Round 41 - Live Jazz and Fusion Night  jazz  london 2026-07-16  0.630618

In [26]:
embedding_search.search("classical orchestra")

,event_name,genre,city,date,score
0,National Symphony Orchestra,classical,vienna,2026-08-14,0.760160
1,National Symphony Orchestra: Harry Potter and ...,classical,vienna,2026-08-27,0.648823
2,Jazz at Lincoln Center Orchestra,other,vienna,2026-09-12,0.619283
3,Tarmo Peltokoski & Hong Kong Philharmonic Orch...,classical,berlin,2026-12-03,0.587713
4,Hook in Concert w/ National Symphony Orchestra,classical,vienna,2026-09-05,0.586347
5,Avond van De Filmmuziek 2026,classical,amsterdam,2026-11-21,0.585098
6,Avond van De Filmmuziek 2026,classical,amsterdam,2026-11-20,0.585098
7,Avond van De Filmmuziek 2026,classical,amsterdam,2026-11-22,0.585098
8,Lindsey Stirling,classical,vienna,2026-07-14,0.579539
9,Kaizers Orchestra,rock,amsterdam,2026-10-02,0.579326

In [27]:
embedding_search.search("museum")

,event_name,genre,city,date,score
0,Twist Museum - London's Home of Illusions PEAK,family,london,2026-07-12,0.488445
1,Twist Museum - London's Home of Illusions PEAK,family,london,2026-07-12,0.488445
2,Twist Museum - London's Home of Illusions PEAK,family,london,2026-07-12,0.488445
3,Twist Museum - London's Home of Illusions PEAK,family,london,2026-07-12,0.488445
4,Twist Museum - London's Home of Illusions PEAK,family,london,2026-07-12,0.488445
5,Twist Museum - London's Home of Illusions PEAK,family,london,2026-07-12,0.488445
6,Twist Museum - London's Home of Illusions PEAK,family,london,2026-07-12,0.488445
7,Twist Museum - London's Home of Illusions PEAK,family,london,2026-07-12,0.488445
8,Twist Museum - London's Home of Illusions PEAK,family,london,2026-07-26,0.488445
9,Twist Museum - London's Home of Illusions PEAK,family,london,2026-07-26,0.488445

In [28]:
embedding_search.search("rock berlin")

,event_name,genre,city,date,score
0,My First Time,rock,berlin,2026-11-01,0.835528
1,Nachtkinder,rock,berlin,2027-02-02,0.811784
2,Mammoth,rock,berlin,2026-11-12,0.805201
3,Tove Lo - ESTRUS,rock,berlin,2026-11-14,0.786839
4,Sace6,rock,berlin,2026-12-01,0.786131
5,The Bausa,rock,berlin,2026-10-28,0.775924
6,DAGNY - Europe 2027,rock,berlin,2027-02-15,0.752936
7,Young The Giant - Victory Garden Tour,rock,berlin,2026-10-19,0.732577
8,"overpass - Elsewhere, Always Album Tour Europe",rock,berlin,2026-09-21,0.718204
9,Jamie Grey - Europe 2026,rock,berlin,2026-10-22,0.717635

In [29]:
embedding_search.search("film festival")

,event_name,genre,city,date,score
0,Rock the Park Music Festival w/ The Lumineers,fairs & festivals,london,2026-07-15,0.529167
1,Future Now - Festivalpass für 3 Konzerte über...,fairs & festivals,berlin,2026-08-01,0.466081
2,Modi,comedy,london,2026-11-03,0.463891
3,Modi,comedy,london,2026-11-01,0.463891
4,Shoot From The Hip - Saturday 18th July,comedy,london,2026-07-18,0.456446
5,Efg Jazz Festival - Samara Joy,jazz,london,2026-11-22,0.455782
6,THE BLACKOUT - 16 JULY - GBEMI OLADIPO,comedy,london,2026-07-16,0.453109
7,THE BLACKOUT - 30 JULY,comedy,london,2026-07-30,0.451129
8,Mon 13th Jul - Grandad & Me Do Standup,comedy,london,2026-07-13,0.450060
9,Hocus Pocus: Film with Live Orchestra,comedy,london,2026-10-25,0.449907

In [32]:
embedding_search.search("music movie")

,event_name,genre,city,date,score
0,Grease: the Immersive Movie Musical,miscellaneous,london,2026-08-01,0.541015
1,Grease: the Immersive Movie Musical,miscellaneous,london,2026-08-22,0.541015
2,Grease: the Immersive Movie Musical,miscellaneous,london,2026-08-26,0.541015
3,Grease: the Immersive Movie Musical,miscellaneous,london,2026-08-19,0.541015
4,Grease: the Immersive Movie Musical,miscellaneous,london,2026-08-30,0.541015
5,Grease: the Immersive Movie Musical,miscellaneous,london,2026-08-29,0.541015
6,Grease: the Immersive Movie Musical,miscellaneous,london,2026-08-21,0.541015
7,Grease: the Immersive Movie Musical,miscellaneous,london,2026-08-29,0.541015
8,Grease: the Immersive Movie Musical,miscellaneous,london,2026-08-23,0.541015
9,Grease: the Immersive Movie Musical,miscellaneous,london,2026-08-23,0.541015

In [33]:
embedding_search.search("family show")

,event_name,genre,city,date,score
0,Mon 13th Jul - Stand Up Comedy Show - Big Bell...,comedy,london,2026-07-13,0.408981
1,Mon 20th Jul - Stand Up Comedy Show - Big Bell...,comedy,london,2026-07-20,0.391373
2,THE FRIDAY NIGHT SHOW!,comedy,london,2026-08-28,0.386063
3,THE FRIDAY NIGHT SHOW!,comedy,london,2026-08-14,0.386063
4,THE FRIDAY NIGHT SHOW!,comedy,london,2026-08-21,0.386063
5,THE FRIDAY NIGHT SHOW!,comedy,london,2026-07-17,0.386063
6,THE FRIDAY NIGHT SHOW!,comedy,london,2026-07-24,0.386063
7,THE FRIDAY NIGHT SHOW!,comedy,london,2026-08-07,0.386063
8,THE FRIDAY NIGHT SHOW!,comedy,london,2026-07-31,0.386063
9,Thurs 20th Aug - Stand Up Comedy Show - Big Be...,comedy,london,2026-08-20,0.384282

In [34]:
embedding_search.search("symphony")

,event_name,genre,city,date,score
0,National Symphony Orchestra,classical,vienna,2026-08-14,0.647478
1,UNDERTALE - The Determination Symphony World Tour,classical,barcelona,2027-02-16,0.639690
2,National Symphony Orchestra: Harry Potter and ...,classical,vienna,2026-08-27,0.603370
3,Kaizers Orchestra,rock,amsterdam,2026-10-02,0.544623
4,Jerry Garcia Symphonic Celebration,rock,vienna,2026-09-04,0.536130
5,ELECTRO SYMPHONY: ORCHESTRA DANCE PARTY,dance/electronic,amsterdam,2027-05-27,0.521249
6,David Garrett - Millennium Symphony Open Air T...,rock,berlin,2026-07-12,0.513560
7,BOUKE - with symphonic orchestra,rock,amsterdam,2027-04-30,0.511085
8,BOUKE - with symphonic orchestra,rock,amsterdam,2027-04-29,0.511085
9,Enigma. Enya. Neoclassica by Mystery Ensemble,classical,london,2026-07-18,0.501006

In [36]:
search.search("symphony")

,event_name,genre,city,date,score
0,National Symphony Orchestra,classical,vienna,2026-08-14,0.505225
1,UNDERTALE - The Determination Symphony World Tour,classical,barcelona,2027-02-16,0.403625
2,Hook in Concert w/ National Symphony Orchestra,classical,vienna,2026-09-05,0.400152
3,ELECTRO SYMPHONY: ORCHESTRA DANCE PARTY,dance/electronic,amsterdam,2027-05-27,0.365695
4,Young Euro Classic 2026 | Youth Symphony Orche...,classical,berlin,2026-08-09,0.356403
5,Young Euro Classic 2026 | Youth Symphony Orche...,classical,berlin,2026-08-01,0.356403
6,David Garrett - Millennium Symphony Open Air T...,rock,berlin,2026-07-12,0.355803
7,National Symphony Orchestra: Harry Potter and ...,classical,vienna,2026-08-27,0.354606
8,David Garrett - Millennium Symphony Open Air T...,rock,berlin,2026-07-12,0.339173
9,Young Euro Classic 2026 | AYSO - Accademia You...,classical,berlin,2026-08-16,0.326050